"""Configuration loading. Every tunable lives in config.yaml; nothing is hardcoded."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml

DEFAULT_CONFIG = "config.yaml"


class Config:
    """Thin dotted-path accessor over the parsed YAML tree."""

    def __init__(self, data: dict[str, Any], root: Path):
        self._data = data
        self.root = root

    def get(self, path: str, default: Any = None) -> Any:
        node: Any = self._data
        for key in path.split("."):
            if not isinstance(node, dict) or key not in node:
                return default
            node = node[key]
        return node

    def require(self, path: str) -> Any:
        value = self.get(path, _MISSING)
        if value is _MISSING:
            raise KeyError(f"missing config key: {path}")
        return value

    @property
    def data_root(self) -> Path:
        """Where generated data lives - downloads, caches, clips, logs.

        Defaults to the project root so a fresh checkout just works, but
        pointing it elsewhere moves every generated byte out of the repo in one
        move. That matters here: the working set reached 30GB, which has no
        business sitting next to 300KB of source.

        SOLOCLIP_DATA overrides the config, so the same config file can be used
        on a machine with different storage without editing it.
        """
        entry = os.environ.get("SOLOCLIP_DATA") or self.get("paths.data_root")
        if not entry:
            return self.root
        return (self.root / str(entry)).resolve()

    def path(self, key: str) -> Path:
        """Resolve a paths.* entry. Generated data hangs off data_root."""
        value = self.require(f"paths.{key}")
        if isinstance(value, list):
            value = value[0]
        return (self.data_root / str(value)).resolve()

    def url_lists(self) -> list[Path]:
        """paths.url_list accepts one file or several, so lists can be added
        without disturbing what has already been queued."""
        value = self.require("paths.url_list")
        entries = value if isinstance(value, list) else [value]
        return [(self.data_root / str(e)).resolve() for e in entries]

    # -- derived directories -------------------------------------------------
    @property
    def work(self) -> Path:
        return self.path("work_dir")

    @property
    def raw_dir(self) -> Path:
        return self.work / "raw"

    @property
    def audio_dir(self) -> Path:
        return self.work / "audio"

    @property
    def meta_dir(self) -> Path:
        return self.work / "meta"

    @property
    def cache_dir(self) -> Path:
        return self.work / "cache"

    @property
    def out_dir(self) -> Path:
        return self.path("out_dir")

    @property
    def audio_out_dir(self) -> Path:
        """Audio-only fallbacks live apart from the video deliverables on purpose."""
        entry = self.get("paths.audio_out_dir")
        if entry:
            return (self.data_root / str(entry)).resolve()
        return self.out_dir.parent / (self.out_dir.name + "_audio")

    @property
    def log_dir(self) -> Path:
        return self.path("log_dir")

    def ensure_dirs(self) -> None:
        for d in (self.raw_dir, self.audio_dir, self.meta_dir, self.cache_dir,
                  self.out_dir, self.audio_out_dir, self.log_dir):
            d.mkdir(parents=True, exist_ok=True)

    @property
    def device(self) -> str:
        want = str(self.get("runtime.device", "cuda"))
        if want == "cuda":
            try:
                import torch

                if not torch.cuda.is_available():
                    return "cpu"
            except Exception:
                return "cpu"
        return want


_MISSING = object()


def _deep_merge(base: dict[str, Any], over: dict[str, Any]) -> dict[str, Any]:
    """Overlay `over` onto `base`, merging nested dicts instead of replacing them."""
    out = dict(base)
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def _read_yaml(path: Path, seen: set[Path] | None = None) -> dict[str, Any]:
    """Read a config, resolving `extends:` so variants only state their differences.

    Without this every list needs a full copy of the file, and a threshold change
    has to be made in each one - which is how they drift apart.
    """
    seen = seen or set()
    path = path.resolve()
    if path in seen:
        raise ValueError(f"circular extends: {path}")
    seen.add(path)
    if not path.exists():
        raise FileNotFoundError(f"config not found: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    parent = data.pop("extends", None)
    if not parent:
        return data
    parent_path = Path(parent)
    if not parent_path.is_absolute():
        parent_path = path.parent / parent_path
    return _deep_merge(_read_yaml(parent_path, seen), data)


def _project_root(start: Path) -> Path:
    """Anchor relative paths to the project, not to wherever the config sits.

    Configs live in several places (repo root, configs/), and resolving paths
    against the config's own directory made the same `work_dir:` mean different
    directories depending on which file was passed to -c.
    """
    for candidate in [start, *start.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    return start


LOCAL_OVERRIDE = "local.yaml"


def load_config(path: str | os.PathLike[str] | None = None) -> Config:
    cfg_path = Path(path or DEFAULT_CONFIG).resolve()
    data = _read_yaml(cfg_path)
    # Machine-specific values (cookie profile paths, storage locations) belong in
    # a gitignored file next to the configs, not in tracked ones - otherwise one
    # person's username ends up in everybody's checkout.
    local = cfg_path.parent / LOCAL_OVERRIDE
    if local.exists() and local != cfg_path:
        data = _deep_merge(data, yaml.safe_load(local.read_text(encoding="utf-8")) or {})
    cfg = Config(data, _project_root(cfg_path.parent))
    _load_dotenv(cfg.root / ".env")
    # hf-xet's transfer backend stalls at 0 bytes on some networks while plain
    # HTTP downloads fine; force the HTTP path. Set HF_HUB_DISABLE_XET=0 to undo.
    os.environ.setdefault("HF_HUB_DISABLE_XET", "1")
    return cfg


def _load_dotenv(path: Path) -> None:
    """Minimal .env reader; existing environment variables always win."""
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def hf_token() -> str | None:
    """Env var first, then whatever `huggingface-cli login` already cached."""
    for key in ("HF_TOKEN", "HUGGINGFACE_TOKEN", "HUGGING_FACE_HUB_TOKEN"):
        if os.environ.get(key):
            return os.environ[key]
    cached = Path.home() / ".cache" / "huggingface" / "token"
    if cached.exists():
        token = cached.read_text(encoding="utf-8").strip()
        if token:
            return token
    return None
